spring:
  profiles:
    thymeleaf:
      cache: false
      prefix: file:src/main/resources/templates/
    devtools:
      livereload:
        enabled: true
      restart:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
custom:
  genFileDirPath: c:/temp/ylwImg/member